const http =require('http')
const fs = require("fs")    
const path = require("path")    
const url = require("url")
const querystring = require("querystring")
const express = require("express")
const app = express()
app.use(express.static(path.))
